version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    # Use a different directory to avoid Windows Docker issues
    volumes:
      - .:/code
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=change_this_in_production
      - DATABASE_URL=sqlite:////app/instance/attendance.db
    # Run as root to avoid permission issues
    user: "root"
    command: gunicorn --bind 0.0.0.0:5000 --workers 1 run:app
    restart: unless-stopped

  # Uncomment the following section if you want to use PostgreSQL instead of SQLite
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=attendance
  #   restart: unless-stopped
  
  # If using PostgreSQL, update the web service environment to:
  # environment:
  #   - FLASK_APP=run.py
  #   - FLASK_ENV=production
  #   - SECRET_KEY=change_this_in_production
  #   - DATABASE_URL=postgresql://postgres:postgres@db:5432/attendance

# Using a bind mount for the entire app directory
